version: "3.3"
 
services:

  php8:
    build: ./php/php8
    container_name: php8
    restart: unless-stopped
    volumes:
      - "./html/php8:/var/www/html/php8"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./log/php8:/var/log/php"

    environment:
      TZ : ${TZ}

  php74:
    build: ./php/php74
    container_name: php74
    restart: unless-stopped
    volumes:
      - "./html/php74:/var/www/html/php74"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./log/php74:/var/log/php"

    environment:
      TZ: ${TZ}


  php73:
    build: ./php/php73
    container_name: php73
    restart: unless-stopped
    volumes:
      - "./html/php73:/var/www/html/php73"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./log/php73:/var/log/php"
    
    environment:
      TZ : ${TZ}

  php56:
    build: ./php/php56
    container_name: php56
    restart: unless-stopped
    volumes:
       - "./html/php56:/var/www/html/php56"
       - "./php/php.ini:/usr/local/etc/php/php.ini"
       - "./log/php56:/var/log/php"
    
    environment:
      TZ : ${TZ}
 
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./html:/var/www/html"
      - "./log/nginx:/var/log/nginx"
      - "./nginx/conf.d:/etc/nginx/conf.d/:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/vhost:/etc/nginx/sites-available/:ro"
      - "./nginx/ssl:/etc/nginx/ssl"

    environment:
      TZ : ${TZ}

    links:
        - php8
        - php56
        - php73
        - php74

