version: "3.3"
 
services:

  php82:
    build: php/php82
    container_name: php82
    restart: unless-stopped
    volumes:
      - "./html/php82:/var/www/html/php82"
      - "./php/php82/php.ini:/usr/local/etc/php/php.ini"
      - "./log/php82:/var/log/php"

    environment:
      TZ : ${TZ}

    networks:
      - code-network

  php74:
    build: ./php/php74
    container_name: php74
    restart: unless-stopped
    volumes:
      - "./html/php74:/var/www/html/php74"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./log/php74:/var/log/php"

    environment:
      TZ: ${TZ}

    networks:
      - code-network


  php73:
    build: ./php/php73
    container_name: php73
    restart: unless-stopped
    volumes:
      - "./html/php73:/var/www/html/php73"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./log/php73:/var/log/php"
    
    environment:
      TZ : ${TZ}

    networks:
      - code-network

  php56:
    build: ./php/php56
    container_name: php56
    restart: unless-stopped
    volumes:
       - "./html/php56:/var/www/html/php56"
       - "./php/php.ini:/usr/local/etc/php/php.ini"
       - "./log/php56:/var/log/php"
    
    environment:
      TZ : ${TZ}

    networks:
      - code-network
 
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./html:/var/www/html"
      - "./log/nginx:/var/log/nginx"
      - "./nginx/conf.d:/etc/nginx/conf.d/:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/vhost:/etc/nginx/sites-available/:ro"
      - "./nginx/ssl:/etc/nginx/ssl"

    environment:
      TZ : ${TZ}

    networks:
      - code-network

    links:
        - php82
        - php56
        - php73
        - php74

networks:
  code-network:
    driver: bridge
