version: "3.3"
 
services:

  db:
    image: mariadb:10.5.3
    container_name: mariadb
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST : "%"
      TZ : ${TZ}
    ports:
      - 3306:3306
    volumes:
      - ./db/var:/var/lib/mysql
      - ./log/db:/var/log/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf

  php8:
    build: ./php/php8
    container_name: php8
    restart: unless-stopped
    volumes:
      - "./html/php8:/var/www/html/php8"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./log/php8:/var/log/php"

    environment:
      DB_ROOT_PW: ${MYSQL_ROOT_PASSWORD}
      TZ : ${TZ}
    
    links:
      - db

  php74:
    build: ./php/php74
    container_name: php74
    restart: unless-stopped
    volumes:
      - "./html/php74:/var/www/html/php74"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./log/php74:/var/log/php"

    environment:
      DB_ROOT_PW: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}

    links:
      - db

  php73:
    build: ./php/php73
    container_name: php73
    restart: unless-stopped
    volumes:
      - "./html/php73:/var/www/html/php73"
      - "./php/php.ini:/usr/local/etc/php/php.ini"
      - "./log/php73:/var/log/php"
    
    environment:
      DB_ROOT_PW: ${MYSQL_ROOT_PASSWORD}
      TZ : ${TZ}
        
    links:
      - db     

  php56:
    build: ./php/php56
    container_name: php56
    restart: unless-stopped
    volumes:
       - "./html/php56:/var/www/html/php56"
       - "./php/php.ini:/usr/local/etc/php/php.ini"
       - "./log/php56:/var/log/php"
    
    environment:
      DB_ROOT_PW: ${MYSQL_ROOT_PASSWORD}
      TZ : ${TZ}
    links:
        - db 
 
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./html:/var/www/html"
      - "./log/nginx:/var/log/nginx"
      - "./nginx/conf.d:/etc/nginx/conf.d/:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/vhost:/etc/nginx/sites-available/:ro"
      - "./nginx/ssl:/etc/nginx/ssl"

    environment:
      TZ : ${TZ}

    links:
        - php8
        - php56
        - php73

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    volumes:
      - "./php/php.ini:/usr/local/etc/php/php.ini"
    ports:
      - 81:80

    links:  
      - db 
